const UserActionTypes = {
  CHANGE_START_DATE: 'CHANGE_START_DATE',
  CHANGE_PERSONAL_ALLOWANCE: 'CHANGE_PERSONAL_ALLOWANCE',

  FETCH_NI_RESULTS_START: 'FETCH_NI_RESULTS_START',
  FETCH_NI_RESULTS_SUCCESS: 'FETCH_NI_RESULTS_SUCCESS',
  FETCH_NI_RESULTS_FAILURE: 'FETCH_NI_RESULTS_FAILURE',

  RESET_DATA: 'RESET_DATA',
};

export default UserActionTypes;
